<a href="https://colab.research.google.com/github/nasarar/Post_Covid19_Vacation_Projection/blob/Joseph/PMV_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
# Step 1: Load the data
covid_19_PMV = pd.read_csv(
    'https://covid.ourworldindata.org/data/owid-covid-data.csv')
covid_19_PMV.head()

  iso_code continent  ... life_expectancy human_development_index
0      AFG      Asia  ...           64.83                   0.511
1      AFG      Asia  ...           64.83                   0.511
2      AFG      Asia  ...           64.83                   0.511
3      AFG      Asia  ...           64.83                   0.511
4      AFG      Asia  ...           64.83                   0.511

[5 rows x 59 columns]

In [4]:
covid_19_PMV.shape

(91026, 59)

In [5]:
pd.options.display.max_columns= 100

In [6]:
covid_19_PMV.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,new_vaccinations_smoothed_per_million,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,0.026,0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

# Info Method

In [7]:
covid_19_PMV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91026 entries, 0 to 91025
Data columns (total 59 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   iso_code                               91026 non-null  object
 1   continent                              86699 non-null  object
 2   location                               91026 non-null  object
 3   date                                   91026 non-null  object
 4   total_cases                            88336 non-null  float64
 5   new_cases                              88335 non-null  float64
 6   new_cases_smoothed                     87328 non-null  float64
 7   total_deaths                           78484 non-null  float64
 8   new_deaths                             78642 non-null  float64
 9   new_deaths_smoothed                    87328 non-null  float64
 10  total_cases_per_million                87863 non-null  float64
 11  new_cases_per_million                  87862 non-null  float64
 12  new_cases_smoothed_per_million         86860 non-null  float64
 13  total_deaths_per_million               78024 non-null  float64
 14  new_deaths_per_million                 78182 non-null  float64
 15  new_deaths_smoothed_per_million        86860 non-null  float64
 16  reproduction_rate                      73367 non-null  float64
 17  icu_patients                           9176 non-null   float64
 18  icu_patients_per_million               9176 non-null   float64
 19  hosp_patients                          11415 non-null  float64
 20  hosp_patients_per_million              11415 non-null  float64
 21  weekly_icu_admissions                  830 non-null    float64
 22  weekly_icu_admissions_per_million      830 non-null    float64
 23  weekly_hosp_admissions                 1446 non-null   float64
 24  weekly_hosp_admissions_per_million     1446 non-null   float64
 25  new_tests                              41186 non-null  float64
 26  total_tests                            40873 non-null  float64
 27  total_tests_per_thousand               40873 non-null  float64
 28  new_tests_per_thousand                 41186 non-null  float64
 29  new_tests_smoothed                     47682 non-null  float64
 30  new_tests_smoothed_per_thousand        47682 non-null  float64
 31  positive_rate                          44444 non-null  float64
 32  tests_per_case                         43850 non-null  float64
 33  tests_units                            49209 non-null  object
 34  total_vaccinations                     12106 non-null  float64
 35  people_vaccinated                      11353 non-null  float64
 36  people_fully_vaccinated                8767 non-null   float64
 37  new_vaccinations                       10184 non-null  float64
 38  new_vaccinations_smoothed              20537 non-null  float64
 39  total_vaccinations_per_hundred         12106 non-null  float64
 40  people_vaccinated_per_hundred          11353 non-null  float64
 41  people_fully_vaccinated_per_hundred    8767 non-null   float64
 42  new_vaccinations_smoothed_per_million  20537 non-null  float64
 43  stringency_index                       77380 non-null  float64
 44  population                             90422 non-null  float64
 45  population_density                     84662 non-null  float64
 46  median_age                             81753 non-null  float64
 47  aged_65_older                          80829 non-null  float64
 48  aged_70_older                          81299 non-null  float64
 49  gdp_per_capita                         81972 non-null  float64
 50  extreme_poverty                        55479 non-null  float64
 51  cardiovasc_death_rate                  82163 non-null  float64
 52  diabetes_prevalence                    84019 non-null  float64
 53  female_smokers                         64338 non-null  float64
 54  male_smokers                           63393 non-null  float64
 55  handwashing_facilities                 41288 non-null  float64
 56  hospital_beds_per_thousand             74934 non-null  float64
 57  life_expectancy                        86432 non-null  float64
 58  human_development_index                82351 non-null  float64
dtypes: float64(54), object(5)
memory usage: 41.0+ MB

# Count method

In [8]:
covid_19_PMV.count()

iso_code                                 91026
continent                                86699
location                                 91026
date                                     91026
total_cases                              88336
new_cases                                88335
new_cases_smoothed                       87328
total_deaths                             78484
new_deaths                               78642
new_deaths_smoothed                      87328
total_cases_per_million                  87863
new_cases_per_million                    87862
new_cases_smoothed_per_million           86860
total_deaths_per_million                 78024
new_deaths_per_million                   78182
new_deaths_smoothed_per_million          86860
reproduction_rate                        73367
icu_patients                              9176
icu_patients_per_million                  9176
hosp_patients                            11415
hosp_patients_per_million                11415
weekly_icu_admissions                      830
weekly_icu_admissions_per_million          830
weekly_hosp_admissions                    1446
weekly_hosp_admissions_per_million        1446
new_tests                                41186
total_tests                              40873
total_tests_per_thousand                 40873
new_tests_per_thousand                   41186
new_tests_smoothed                       47682
new_tests_smoothed_per_thousand          47682
positive_rate                            44444
tests_per_case                           43850
tests_units                              49209
total_vaccinations                       12106
people_vaccinated                        11353
people_fully_vaccinated                   8767
new_vaccinations                         10184
new_vaccinations_smoothed                20537
total_vaccinations_per_hundred           12106
people_vaccinated_per_hundred            11353
people_fully_vaccinated_per_hundred       8767
new_vaccinations_smoothed_per_million    20537
stringency_index                         77380
population                               90422
population_density                       84662
median_age                               81753
aged_65_older                            80829
aged_70_older                            81299
gdp_per_capita                           81972
extreme_poverty                          55479
cardiovasc_death_rate                    82163
diabetes_prevalence                      84019
female_smokers                           64338
male_smokers                             63393
handwashing_facilities                   41288
hospital_beds_per_thousand               74934
life_expectancy                          86432
human_development_index                  82351
dtype: int64

In [9]:
covid_19_PMV_missing= covid_19_PMV.isna()
covid_19_PMV_missing.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,new_vaccinations_smoothed_per_million,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,False,False,False,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False
1,False,False,False,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False
2,False,False,False,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False
4,False,False,False,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False

In [10]:
covid_19_PMV_missing.dtypes

iso_code                                 bool
continent                                bool
location                                 bool
date                                     bool
total_cases                              bool
new_cases                                bool
new_cases_smoothed                       bool
total_deaths                             bool
new_deaths                               bool
new_deaths_smoothed                      bool
total_cases_per_million                  bool
new_cases_per_million                    bool
new_cases_smoothed_per_million           bool
total_deaths_per_million                 bool
new_deaths_per_million                   bool
new_deaths_smoothed_per_million          bool
reproduction_rate                        bool
icu_patients                             bool
icu_patients_per_million                 bool
hosp_patients                            bool
hosp_patients_per_million                bool
weekly_icu_admissions                    bool
weekly_icu_admissions_per_million        bool
weekly_hosp_admissions                   bool
weekly_hosp_admissions_per_million       bool
new_tests                                bool
total_tests                              bool
total_tests_per_thousand                 bool
new_tests_per_thousand                   bool
new_tests_smoothed                       bool
new_tests_smoothed_per_thousand          bool
positive_rate                            bool
tests_per_case                           bool
tests_units                              bool
total_vaccinations                       bool
people_vaccinated                        bool
people_fully_vaccinated                  bool
new_vaccinations                         bool
new_vaccinations_smoothed                bool
total_vaccinations_per_hundred           bool
people_vaccinated_per_hundred            bool
people_fully_vaccinated_per_hundred      bool
new_vaccinations_smoothed_per_million    bool
stringency_index                         bool
population                               bool
population_density                       bool
median_age                               bool
aged_65_older                            bool
aged_70_older                            bool
gdp_per_capita                           bool
extreme_poverty                          bool
cardiovasc_death_rate                    bool
diabetes_prevalence                      bool
female_smokers                           bool
male_smokers                             bool
handwashing_facilities                   bool
hospital_beds_per_thousand               bool
life_expectancy                          bool
human_development_index                  bool
dtype: object

# Sum method

In [11]:
covid_19_PMV_num_missing= covid_19_PMV_missing.sum()
covid_19_PMV_num_missing

iso_code                                     0
continent                                 4327
location                                     0
date                                         0
total_cases                               2690
new_cases                                 2691
new_cases_smoothed                        3698
total_deaths                             12542
new_deaths                               12384
new_deaths_smoothed                       3698
total_cases_per_million                   3163
new_cases_per_million                     3164
new_cases_smoothed_per_million            4166
total_deaths_per_million                 13002
new_deaths_per_million                   12844
new_deaths_smoothed_per_million           4166
reproduction_rate                        17659
icu_patients                             81850
icu_patients_per_million                 81850
hosp_patients                            79611
hosp_patients_per_million                79611
weekly_icu_admissions                    90196
weekly_icu_admissions_per_million        90196
weekly_hosp_admissions                   89580
weekly_hosp_admissions_per_million       89580
new_tests                                49840
total_tests                              50153
total_tests_per_thousand                 50153
new_tests_per_thousand                   49840
new_tests_smoothed                       43344
new_tests_smoothed_per_thousand          43344
positive_rate                            46582
tests_per_case                           47176
tests_units                              41817
total_vaccinations                       78920
people_vaccinated                        79673
people_fully_vaccinated                  82259
new_vaccinations                         80842
new_vaccinations_smoothed                70489
total_vaccinations_per_hundred           78920
people_vaccinated_per_hundred            79673
people_fully_vaccinated_per_hundred      82259
new_vaccinations_smoothed_per_million    70489
stringency_index                         13646
population                                 604
population_density                        6364
median_age                                9273
aged_65_older                            10197
aged_70_older                             9727
gdp_per_capita                            9054
extreme_poverty                          35547
cardiovasc_death_rate                     8863
diabetes_prevalence                       7007
female_smokers                           26688
male_smokers                             27633
handwashing_facilities                   49738
hospital_beds_per_thousand               16092
life_expectancy                           4594
human_development_index                   8675
dtype: int64

In [12]:
len(covid_19_PMV)

91026

In [13]:
covid_19_PMV_mean= covid_19_PMV_num_missing/len(covid_19_PMV)
covid_19_PMV_mean

iso_code                                 0.000000
continent                                0.047536
location                                 0.000000
date                                     0.000000
total_cases                              0.029552
new_cases                                0.029563
new_cases_smoothed                       0.040626
total_deaths                             0.137785
new_deaths                               0.136049
new_deaths_smoothed                      0.040626
total_cases_per_million                  0.034748
new_cases_per_million                    0.034759
new_cases_smoothed_per_million           0.045767
total_deaths_per_million                 0.142838
new_deaths_per_million                   0.141103
new_deaths_smoothed_per_million          0.045767
reproduction_rate                        0.194000
icu_patients                             0.899194
icu_patients_per_million                 0.899194
hosp_patients                            0.874596
hosp_patients_per_million                0.874596
weekly_icu_admissions                    0.990882
weekly_icu_admissions_per_million        0.990882
weekly_hosp_admissions                   0.984114
weekly_hosp_admissions_per_million       0.984114
new_tests                                0.547536
total_tests                              0.550974
total_tests_per_thousand                 0.550974
new_tests_per_thousand                   0.547536
new_tests_smoothed                       0.476172
new_tests_smoothed_per_thousand          0.476172
positive_rate                            0.511744
tests_per_case                           0.518270
tests_units                              0.459396
total_vaccinations                       0.867005
people_vaccinated                        0.875277
people_fully_vaccinated                  0.903687
new_vaccinations                         0.888120
new_vaccinations_smoothed                0.774383
total_vaccinations_per_hundred           0.867005
people_vaccinated_per_hundred            0.875277
people_fully_vaccinated_per_hundred      0.903687
new_vaccinations_smoothed_per_million    0.774383
stringency_index                         0.149913
population                               0.006635
population_density                       0.069914
median_age                               0.101872
aged_65_older                            0.112023
aged_70_older                            0.106860
gdp_per_capita                           0.099466
extreme_poverty                          0.390515
cardiovasc_death_rate                    0.097368
diabetes_prevalence                      0.076978
female_smokers                           0.293191
male_smokers                             0.303573
handwashing_facilities                   0.546415
hospital_beds_per_thousand               0.176785
life_expectancy                          0.050469
human_development_index                  0.095302
dtype: float64

In [14]:
covid_19_PMV.isna().mean().round(4) * 100

iso_code                                  0.00
continent                                 4.75
location                                  0.00
date                                      0.00
total_cases                               2.96
new_cases                                 2.96
new_cases_smoothed                        4.06
total_deaths                             13.78
new_deaths                               13.60
new_deaths_smoothed                       4.06
total_cases_per_million                   3.47
new_cases_per_million                     3.48
new_cases_smoothed_per_million            4.58
total_deaths_per_million                 14.28
new_deaths_per_million                   14.11
new_deaths_smoothed_per_million           4.58
reproduction_rate                        19.40
icu_patients                             89.92
icu_patients_per_million                 89.92
hosp_patients                            87.46
hosp_patients_per_million                87.46
weekly_icu_admissions                    99.09
weekly_icu_admissions_per_million        99.09
weekly_hosp_admissions                   98.41
weekly_hosp_admissions_per_million       98.41
new_tests                                54.75
total_tests                              55.10
total_tests_per_thousand                 55.10
new_tests_per_thousand                   54.75
new_tests_smoothed                       47.62
new_tests_smoothed_per_thousand          47.62
positive_rate                            51.17
tests_per_case                           51.83
tests_units                              45.94
total_vaccinations                       86.70
people_vaccinated                        87.53
people_fully_vaccinated                  90.37
new_vaccinations                         88.81
new_vaccinations_smoothed                77.44
total_vaccinations_per_hundred           86.70
people_vaccinated_per_hundred            87.53
people_fully_vaccinated_per_hundred      90.37
new_vaccinations_smoothed_per_million    77.44
stringency_index                         14.99
population                                0.66
population_density                        6.99
median_age                               10.19
aged_65_older                            11.20
aged_70_older                            10.69
gdp_per_capita                            9.95
extreme_poverty                          39.05
cardiovasc_death_rate                     9.74
diabetes_prevalence                       7.70
female_smokers                           29.32
male_smokers                             30.36
handwashing_facilities                   54.64
hospital_beds_per_thousand               17.68
life_expectancy                           5.05
human_development_index                   9.53
dtype: float64

In [15]:
covid_19_filtered= covid_19_PMV[['location','date','people_vaccinated','people_fully_vaccinated','population','population_density','gdp_per_capita']]
covid_19_filtered

,location,date,people_vaccinated,people_fully_vaccinated,population,population_density,gdp_per_capita
0,Afghanistan,2020-02-24,NaN,NaN,38928341.0,54.422,1803.987
1,Afghanistan,2020-02-25,NaN,NaN,38928341.0,54.422,1803.987
2,Afghanistan,2020-02-26,NaN,NaN,38928341.0,54.422,1803.987
3,Afghanistan,2020-02-27,NaN,NaN,38928341.0,54.422,1803.987
4,Afghanistan,2020-02-28,NaN,NaN,38928341.0,54.422,1803.987
...,...,...,...,...,...,...,...
91021,Zimbabwe,2021-05-20,615296.0,252100.0,14862927.0,42.729,1899.775
91022,Zimbabwe,2021-05-21,624665.0,263263.0,14862927.0,42.729,1899.775
91023,Zimbabwe,2021-05-22,630348.0,273725.0,14862927.0,42.729,1899.775
91024,Zimbabwe,2021-05-23,632496.0,278537.0,14862927.0,42.729,1899.775
91025,Zimbabwe,2021-05-24,633635.0,281286.0,14862927.0,42.729,1899.775

In [16]:
covid_19_filtered.dropna(inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [17]:
covid_19_counts= covid_19_filtered["location"].value_counts()
covid_19_counts

World        149
Germany      149
Belgium      146
Israel       141
Canada       139
            ...
Uganda         1
Mauritius      1
Bahamas        1
Australia      1
Djibouti       1
Name: location, Length: 149, dtype: int64

In [18]:
covid_19_counts[covid_19_counts>1].index

Index(['World', 'Germany', 'Belgium', 'Israel', 'Canada', 'Slovenia',
       'United Kingdom', 'Denmark', 'Estonia', 'Norway',
       ...
       'Antigua and Barbuda', 'Jamaica', 'Kyrgyzstan', 'Brunei', 'Mauritania',
       'Mozambique', 'Congo', 'Senegal', 'Mali', 'Bosnia and Herzegovina'],
      dtype='object', length=138)

In [19]:
covid_19_filtered2=covid_19_filtered["location"].isin(covid_19_counts[covid_19_counts>1].index)
covid_19_filtered2

442      True
451      True
455      True
1266     True
1273     True
         ...
91021    True
91022    True
91023    True
91024    True
91025    True
Name: location, Length: 7350, dtype: bool

In [20]:
covid_19_filter= covid_19_filtered[covid_19_filtered2]
covid_19_filter

,location,date,people_vaccinated,people_fully_vaccinated,population,population_density,gdp_per_capita
442,Afghanistan,2021-05-11,448878.0,55624.0,38928341.0,54.422,1803.987
451,Afghanistan,2021-05-20,470341.0,77560.0,38928341.0,54.422,1803.987
455,Afghanistan,2021-05-24,476367.0,96910.0,38928341.0,54.422,1803.987
1266,Albania,2021-02-02,549.0,1.0,2877800.0,104.871,11803.431
1273,Albania,2021-02-09,689.0,438.0,2877800.0,104.871,11803.431
...,...,...,...,...,...,...,...
91021,Zimbabwe,2021-05-20,615296.0,252100.0,14862927.0,42.729,1899.775
91022,Zimbabwe,2021-05-21,624665.0,263263.0,14862927.0,42.729,1899.775
91023,Zimbabwe,2021-05-22,630348.0,273725.0,14862927.0,42.729,1899.775
91024,Zimbabwe,2021-05-23,632496.0,278537.0,14862927.0,42.729,1899.775
91025,Zimbabwe,2021-05-24,633635.0,281286.0,14862927.0,42.729,1899.775

In [21]:
covid_19_filter['location'].unique()

array(['Afghanistan', 'Albania', 'Angola', 'Antigua and Barbuda',
       'Argentina', 'Aruba', 'Austria', 'Azerbaijan', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize',
       'Bermuda', 'Bolivia', 'Bosnia and Herzegovina', 'Brazil', 'Brunei',
       'Bulgaria', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Chile', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cyprus', 'Czechia', 'Denmark',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Estonia', 'Finland', 'France',
       'Gabon', 'Georgia', 'Germany', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guyana', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan',
       'Laos', 'Latvia', 'Lebanon', 'Lithuania', 'Luxembourg', 'Macao',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mexico',
       'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand',
       'Niger', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Saint Kitts and Nevis',
       'Saint Lucia', 'San Marino', 'Senegal', 'Serbia', 'Seychelles',
       'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'South Africa',
       'South Korea', 'Spain', 'Sri Lanka', 'Suriname', 'Sweden',
       'Switzerland', 'Thailand', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vietnam', 'World', 'Zambia', 'Zimbabwe'], dtype=object)

In [22]:
covid_19_final=covid_19_filter[covid_19_filter.location != 'World']
covid_19_final

,location,date,people_vaccinated,people_fully_vaccinated,population,population_density,gdp_per_capita
442,Afghanistan,2021-05-11,448878.0,55624.0,38928341.0,54.422,1803.987
451,Afghanistan,2021-05-20,470341.0,77560.0,38928341.0,54.422,1803.987
455,Afghanistan,2021-05-24,476367.0,96910.0,38928341.0,54.422,1803.987
1266,Albania,2021-02-02,549.0,1.0,2877800.0,104.871,11803.431
1273,Albania,2021-02-09,689.0,438.0,2877800.0,104.871,11803.431
...,...,...,...,...,...,...,...
91021,Zimbabwe,2021-05-20,615296.0,252100.0,14862927.0,42.729,1899.775
91022,Zimbabwe,2021-05-21,624665.0,263263.0,14862927.0,42.729,1899.775
91023,Zimbabwe,2021-05-22,630348.0,273725.0,14862927.0,42.729,1899.775
91024,Zimbabwe,2021-05-23,632496.0,278537.0,14862927.0,42.729,1899.775
91025,Zimbabwe,2021-05-24,633635.0,281286.0,14862927.0,42.729,1899.775

In [23]:
covid_19_final['location'].unique()

array(['Afghanistan', 'Albania', 'Angola', 'Antigua and Barbuda',
       'Argentina', 'Aruba', 'Austria', 'Azerbaijan', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize',
       'Bermuda', 'Bolivia', 'Bosnia and Herzegovina', 'Brazil', 'Brunei',
       'Bulgaria', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Chile', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cyprus', 'Czechia', 'Denmark',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Estonia', 'Finland', 'France',
       'Gabon', 'Georgia', 'Germany', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guyana', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan',
       'Laos', 'Latvia', 'Lebanon', 'Lithuania', 'Luxembourg', 'Macao',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mexico',
       'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand',
       'Niger', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Saint Kitts and Nevis',
       'Saint Lucia', 'San Marino', 'Senegal', 'Serbia', 'Seychelles',
       'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'South Africa',
       'South Korea', 'Spain', 'Sri Lanka', 'Suriname', 'Sweden',
       'Switzerland', 'Thailand', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vietnam', 'Zambia', 'Zimbabwe'], dtype=object)

In [24]:
covid_19_final.to_csv('covid_19_ready_PMV.csv')